In [1]:
import numpy as np

### i) Create a one-dimensional array and perform all operations


In [80]:
import numpy as np

# np.zeros()
# np.ones
# np.full
# np.eye
# np.empty()
# np.hstack
# np.vstack
# np.arange()
# np.linspace()
# Arithmetic operations 
# (np.add(), np.subtract(), np.multiply(), np.divide(), np.power(), 
#  np.reciprocal(), np.mod()) 

a = np.array([2,3,4,6])
b = np.array([4,5,6,7])
print("a is: \n",a)
print("\n")
print("b is : \n",b)

print(np.zeros(a.shape))

print(np.ones(a.shape))

print(np.full((a.shape),3)) # np.full(shape,element to full)
print("\n\n")

print(np.eye(3,dtype="int")) # np.eye(no.of rows) creates Identity matrix
print("\n")

v1 = np.arange(1,10,2) # np.arange(start, stop, size.ofsteps)
print(v1)
print("\n")

print(np.linspace(1,10,3)) # np.linspace(start, stop, no. of steps)
print("\n\n")

# ARITHMETIC OPERATIONS

print("Arithmetic operations:\n\n")
print("np.add(a,b) is: \n",np.add(a,b))
print("\n")
print("np.subtract(a,b) is: \n",np.subtract(a,b))
print("\n")
print("np.multiply(a,b) is: \n",np.multiply(a,b))
print("\n")
print("np.divide(a,b) is: \n",np.divide(a,b))
print("\n")
print("np.power(a,b) is:\n",np.power(a,b))
print("\n")
print("np.mod(a,b) is:\n",np.mod(a,b))
print("\n")
print("np.remainder(a,b) is:\n",np.remainder(a,b))
print("\n")
print("np.sqrt(a) is:\n",np.round_(np.sqrt(a),4))
print("\n")

v1 = np.arange(1,10,2)
print(v1)
v2 = np.arange(10,20,2)
print(v2)
print("stacking vertically:  ",np.vstack((v1,v2))) # no.of elements must be same in two arrays
print("Stacking Horizontally: ",np.hstack((v1,v2)))


a is: 
 [2 3 4 6]


b is : 
 [4 5 6 7]
[0. 0. 0. 0.]
[1. 1. 1. 1.]
[3 3 3 3]



[[1 0 0]
 [0 1 0]
 [0 0 1]]


[1 3 5 7 9]


[ 1.   5.5 10. ]



Arithmetic operations:


np.add(a,b) is: 
 [ 6  8 10 13]


np.subtract(a,b) is: 
 [-2 -2 -2 -1]


np.multiply(a,b) is: 
 [ 8 15 24 42]


np.divide(a,b) is: 
 [0.5        0.6        0.66666667 0.85714286]


np.power(a,b) is:
 [    16    243   4096 279936]


np.mod(a,b) is:
 [2 3 4 6]


np.remainder(a,b) is:
 [2 3 4 6]


np.sqrt(a) is:
 [1.4142 1.7321 2.     2.4495]


[1 3 5 7 9]
[10 12 14 16 18]
stacking vertically:   [[ 1  3  5  7  9]
 [10 12 14 16 18]]
Stacking Horizontally:  [ 1  3  5  7  9 10 12 14 16 18]


### ii) Create multi-dimensional arrays and find its shape & dimension


In [81]:
a = np.array([[1,2,34],[4,5,6]])
print("a is : \n",a)
b = np.array([[[1,2,3],[3,4,5],[33,44,55]]])
print("b is : \n",b)
print(a.ndim)
print(b.ndim)
print(a.shape)
print(b.shape)


a is : 
 [[ 1  2 34]
 [ 4  5  6]]
b is : 
 [[[ 1  2  3]
  [ 3  4  5]
  [33 44 55]]]
2
3
(2, 3)
(1, 3, 3)


### iii) Create a matrix full of zeros and ones


In [82]:
a = np.array([2,3,4,6])
b = np.array([4,5,6,7])
print("a is: \n",a)
print("\n")
print("b is : \n",b)

print(np.zeros(a.shape))

print(np.ones(a.shape))

a is: 
 [2 3 4 6]


b is : 
 [4 5 6 7]
[0. 0. 0. 0.]
[1. 1. 1. 1.]


### iv) Reshape and flatten data in the array

In [83]:
a = np.arange(32).reshape(4,8)
print("a is: \n",a)

c = np.array([[1,2,3],[4,5,6]])
print("before flattening:\n",c)
b = c.flatten() # array_name.flatten()
print("After Flattening: \n ",b)

a is: 
 [[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]
 [16 17 18 19 20 21 22 23]
 [24 25 26 27 28 29 30 31]]
before flattening:
 [[1 2 3]
 [4 5 6]]
After Flattening: 
  [1 2 3 4 5 6]


### v) Perform Arithmetic operations on Multi dimensional arrays

In [58]:
a = np.array([[1,2,4],[5,5,5]])
b = np.array([[1,2,4],[4,4,4]])
print(np.add(a,b))
print(np.subtract(a,b))
print(np.multiply(a,b))
print(np.divide(a,b))
print(np.power(a,b))
print(np.mod(a,b))
print(np.round_(np.sqrt(a),2))
print(np.remainder(a,b))

[[2 4 8]
 [9 9 9]]
[[0 0 0]
 [1 1 1]]
[[ 1  4 16]
 [20 20 20]]
[[1.   1.   1.  ]
 [1.25 1.25 1.25]]
[[  1   4 256]
 [625 625 625]]
[[0 0 0]
 [1 1 1]]
[[1.   1.41 2.  ]
 [2.24 2.24 2.24]]
[[0 0 0]
 [1 1 1]]


### vi) Append data vertically and horizontally. 

In [12]:
v1 = np.arange(1,10,2)
print(v1)
v2 = np.arange(10,20,2)
print(v2,'\n')

# it takes only one positional args and no.of elements must be same in two arrays

print("stacking vertically: \n ",np.vstack((v1,v2))) 
print("Stacking Horizontally: \n",np.hstack((v1,v2)))

[1 3 5 7 9]
[10 12 14 16 18] 

stacking vertically: 
  [[ 1  3  5  7  9]
 [10 12 14 16 18]]
Stacking Horizontally: 
 [ 1  3  5  7  9 10 12 14 16 18]


### vii) Apply indexing and slicing on array.

In [30]:
# 1d array indexing

a = np.array([1,2,44,32])
print(a)
print('---------')
print(a[0])
print(a[2])

# 2d array indexing

a = np.array([[1,2,3],[4,5,6]])
print(a)
print('********')
print(a[0,1])
print(a[1,2])

# 3d array indexing

a = np.array([[[1,2,3],[4,5,6],[7,8,9]],
              [[3,5,4],[3,2,1],[0,9,8]]])
print(a)
print('--------')
print("a[0,0,2] is : ",a[0,0,2])

# fancy indexing : It allows us to use an array of indices to access multiple array ele's at once. 

# one-d
a = np.linspace(10,25,6)
print(a,'\n')
print(a[[0,1,2]])

# two-d
a = np.arange(24).reshape(4,6)
print(a,'\n')
print(a[0,3])
print(a[[0,3,2]],'\n')

# three-d
a = np.array([[[1,2],[3,4],[5,6]],[[1,1],[2,2],[3,3]]])
print(a,'\n')
print(a[1,0,0])
print(a[[1,0,0]])

print(a[[1,2,3]]) #np.argsort sorts the elements and return their sorted indices
print(a[np.argsort(a)])


[ 1  2 44 32]
---------
1
44
[[1 2 3]
 [4 5 6]]
********
2
6
[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[3 5 4]
  [3 2 1]
  [0 9 8]]]
--------
a[0,0,2] is :  3
[10. 13. 16. 19. 22. 25.] 

[10. 13. 16.]
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]] 

3
[[ 0  1  2  3  4  5]
 [18 19 20 21 22 23]
 [12 13 14 15 16 17]] 

[[[1 2]
  [3 4]
  [5 6]]

 [[1 1]
  [2 2]
  [3 3]]] 

1
[[[1 1]
  [2 2]
  [3 3]]

 [[1 2]
  [3 4]
  [5 6]]

 [[1 2]
  [3 4]
  [5 6]]]


In [31]:
# boolean indexing

names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will'])

data = np.random.randn(5, 4) 
# array of defined shape filled with random floating point samples from std normal dist

print(names,names.dtype,data,data.dtype)
print(names == 'Bob')
print(data[names=='Bob'])
print(names != 'Bob')

mask = (names == 'Bob') | (names == 'Will')
print('mask=   ',mask)

print(data[data<0])

#set all of the negative values in data to 0 we need only do

data[data<0]=0
print(data)
#The boolean array must be of the same length as the axis it’s indexing


['Bob' 'Joe' 'Will' 'Bob' 'Will'] <U4 [[ 0.36106325  0.05634034 -0.62098464  0.12450862]
 [-0.34649026  0.63847415 -0.59367001  0.20043476]
 [ 0.39675963 -0.28502308  0.67767115 -0.62711466]
 [-0.44220613 -1.06009177 -0.32686534  0.8918691 ]
 [ 0.39056401  0.52242812  0.6570776  -0.17514675]] float64
[ True False False  True False]
[[ 0.36106325  0.05634034 -0.62098464  0.12450862]
 [-0.44220613 -1.06009177 -0.32686534  0.8918691 ]]
[False  True  True False  True]
mask=    [ True False  True  True  True]
[-0.62098464 -0.34649026 -0.59367001 -0.28502308 -0.62711466 -0.44220613
 -1.06009177 -0.32686534 -0.17514675]
[[0.36106325 0.05634034 0.         0.12450862]
 [0.         0.63847415 0.         0.20043476]
 [0.39675963 0.         0.67767115 0.        ]
 [0.         0.         0.         0.8918691 ]
 [0.39056401 0.52242812 0.6570776  0.        ]]


In [32]:
#slicing

s = np.array([1,2,3,4,66,51])  # 1d array slicing
s[2:5:1]  # x[i : j-1: k]

#both are same

print(s[::-1])
print(s[:])

print(s[1:-1])

print("\n")

[51 66  4  3  2  1]
[ 1  2  3  4 66 51]
[ 2  3  4 66]




### viii) Use statistical functions on array - min,max,mean,median and std.

In [50]:
a = np.array([1,2,3,4])
print(a.min())
print(np.min(a))
print(np.max(a))

a = np.arange(24).reshape(4,6)
print(a,'\n')
print(np.min(a,axis=1))# axis =1 col-wise
print(np.max(a,axis = 1))


1
1
4
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]] 

[ 0  6 12 18]
[ 5 11 17 23]


In [39]:
print(np.mean(a,axis = 1))
print(np.median(a,axis = 0))
print(np.std(a,axis = 1))


[ 2.5  8.5 14.5 20.5]
[ 9. 10. 11. 12. 13. 14.]
[1.70782513 1.70782513 1.70782513 1.70782513]


### ix) Dot matrix product of two arrays.

In [44]:
a = np.arange(20).reshape(4,5)
print(a)
b = np.arange(20).reshape(5,4)
print(b)
print(np.matmul(a,b))
print(np.dot(a,b))
print(a@b)


[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]
[[120 130 140 150]
 [320 355 390 425]
 [520 580 640 700]
 [720 805 890 975]]
[[120 130 140 150]
 [320 355 390 425]
 [520 580 640 700]
 [720 805 890 975]]
[[120 130 140 150]
 [320 355 390 425]
 [520 580 640 700]
 [720 805 890 975]]


### x) Compute Eigen Values of a matrix

In [79]:
a = np.array([[1,3,5],[7,9,2],[4,6,8]])
np.linalg.eig(a)

EigResult(eigenvalues=array([15.4422907 , -0.98661655,  3.54432584]), eigenvectors=array([[ 0.36886455,  0.81664483,  0.37173179],
       [ 0.61669356, -0.57673733, -0.7003462 ],
       [ 0.69543367,  0.02157037,  0.60936908]]))

### xi) Solve a linear matrix equation such as 3*x0 + x1 = 9 , x0 + 2*x1 = 8

In [72]:
# define co-efficient matrix 3,1 and 1,2
a = np.array([[3,1],[1,2]])
b = np.array([9,8])
print(np.linalg.solve(a,b))

[2. 3.]


### xii) compute multiplicative inverse of a matrix.

In [61]:
a = np.array([[1,3,5],[7,9,2],[4,6,8]])
print(np.linalg.inv(a))

[[-1.11111111 -0.11111111  0.72222222]
 [ 0.88888889  0.22222222 -0.61111111]
 [-0.11111111 -0.11111111  0.22222222]]


### xiii) compute the rank of a matrix.

In [76]:
# The number of linearly independent columns ( or rows ) of a matrix

a = np.array([[1,2],[3,4],[5,6]])
print(np.linalg.matrix_rank(a))

2


### xiv) compute the determinant of an array.

In [62]:
a = np.array([[1,3,5],[2,4,5],[4,6,8]])
print(np.linalg.det(a))

-6.0


### xv) Perform transpose and change of axes operations on arrays.

In [70]:
a = np.arange(12).reshape(3,4)
print(a)
print(a.T)
print(np.transpose(a))

print(np.swapaxes(a,0,1)) # np.swapaxes(array, axis1, axis2)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


### xvi) Perform Splitting operations on arrays.

In [60]:
a = np.arange(24).reshape(6,4)
print(np.vsplit(a,3))
b = np.arange(12).reshape(4,3)
print(np.hsplit(b,3))

[array([[0, 1, 2, 3],
       [4, 5, 6, 7]]), array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]]), array([[16, 17, 18, 19],
       [20, 21, 22, 23]])]
[array([[0],
       [3],
       [6],
       [9]]), array([[ 1],
       [ 4],
       [ 7],
       [10]]), array([[ 2],
       [ 5],
       [ 8],
       [11]])]
